export {default as html} from './html.svg';
export {default as css} from './css.svg';
export {default as scss} from './sass.svg';
export {default as js} from './javascript.svg';
export {default as ts} from './typescript.svg';
export {default as react} from './react.svg';
export {default as router} from './react-router.svg';
export {default as redux} from './redux.svg';
export {default as form} from './reactHookForm.svg';
export {default as axios} from './axios.svg';
export {default as sc} from './sc.png';
export {default as mui} from './material-ui.svg';
export {default as next} from './next.svg';
export {default as jest} from './jest.svg';
export {default as webpack} from './webpack.svg';
export {default as nodejs} from './nodejs.svg';
export {default as express} from './express.svg';
export {default as mongodb} from './mongodb.svg';
export {default as nest} from './nest.svg';
export {default as figma} from './figma.svg';
export {default as illustrator} from './illustrator.svg';
export {default as photoshop} from './photoshop.svg';
export {default as after_effects} from './after_effects.svg';
export {default as ant} from './ant.svg'
export {default as ubuntu} from './ubuntu.svg'
export {default as nginx} from './nginx.svg'
export {default as passport} from './passport.svg'
export {default as query} from './query.svg'
export {default as cinema} from './cinema.png'
export {default as jwt} from './jwt.svg'