export {default as MainLayout} from './Layouts/MainLayout'
export {default as Header} from './Header/Header'
export {default as Footer} from './Footer/Footer'
export {default as MainPage} from './MainPage/MainPage'
export {default as PageTitle} from './Layouts/PageTitle'
export {default as BlogPage} from './BlogPage/BlogPage'
